[build]
  # Build command.
  command = "yarn run netlify-build"

  # Publish diretory
  publish = "build/"

  # Ignore deploys for dependabot branches
  ignore = "node ignore_build.js"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
